[package]
name = "wasmer-examples/python-wasmer-starter"
version = "0.2.1"
description = "Python HTTP Server Wasmer starter package"
readme = "README.md"
repository = "https://github.com/wasmerio/python-wasmer-starter"

[dependencies]
"wasmer/python" = "^3.12.6"

[fs]
"/src" = "./src"

[[command]]
name = "script"
module = "wasmer/python:python"
runner = "wasi"

[command.annotations.wasi]
main-args = ["/src/main.py"]
